# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'console.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Console(object):
    def setupUi(self, Console):
        Console.setObjectName("Console")
        Console.resize(500, 220)
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        Console.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Console)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 500, 220))
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 220))
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 220))
        self.tabWidget.setObjectName("tabWidget")
        self.controllerTab = QtWidgets.QWidget()
        self.controllerTab.setObjectName("controllerTab")
        self.delayLbl = QtWidgets.QLabel(self.controllerTab)
        self.delayLbl.setGeometry(QtCore.QRect(20, 140, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(16)
        self.delayLbl.setFont(font)
        self.delayLbl.setObjectName("delayLbl")
        self.visualizeBtn = QtWidgets.QPushButton(self.controllerTab)
        self.visualizeBtn.setEnabled(False)
        self.visualizeBtn.setGeometry(QtCore.QRect(250, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(16)
        self.visualizeBtn.setFont(font)
        self.visualizeBtn.setObjectName("visualizeBtn")
        self.speedSldr = QtWidgets.QSlider(self.controllerTab)
        self.speedSldr.setGeometry(QtCore.QRect(170, 140, 221, 31))
        self.speedSldr.setOrientation(QtCore.Qt.Horizontal)
        self.speedSldr.setObjectName("speedSldr")
        self.comboBox = QtWidgets.QComboBox(self.controllerTab)
        self.comboBox.setGeometry(QtCore.QRect(160, 10, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.generateBtn = QtWidgets.QPushButton(self.controllerTab)
        self.generateBtn.setGeometry(QtCore.QRect(20, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        self.generateBtn.setFont(font)
        self.generateBtn.setObjectName("generateBtn")
        self.algorithmLbl = QtWidgets.QLabel(self.controllerTab)
        self.algorithmLbl.setGeometry(QtCore.QRect(20, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(16)
        self.algorithmLbl.setFont(font)
        self.algorithmLbl.setObjectName("algorithmLbl")
        self.stepDelayValueLbl = QtWidgets.QLabel(self.controllerTab)
        self.stepDelayValueLbl.setGeometry(QtCore.QRect(410, 140, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stepDelayValueLbl.setFont(font)
        self.stepDelayValueLbl.setObjectName("stepDelayValueLbl")
        self.tabWidget.addTab(self.controllerTab, "")
        self.visualizationControlsTab = QtWidgets.QWidget()
        self.visualizationControlsTab.setObjectName("visualizationControlsTab")
        self.resetLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.resetLbl.setGeometry(QtCore.QRect(30, 110, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.resetLbl.setFont(font)
        self.resetLbl.setObjectName("resetLbl")
        self.skipLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.skipLbl.setGeometry(QtCore.QRect(30, 70, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.skipLbl.setFont(font)
        self.skipLbl.setObjectName("skipLbl")
        self.endLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.endLbl.setGeometry(QtCore.QRect(30, 30, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endLbl.setFont(font)
        self.endLbl.setObjectName("endLbl")
        self.endExplLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.endExplLbl.setGeometry(QtCore.QRect(330, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endExplLbl.setFont(font)
        self.endExplLbl.setObjectName("endExplLbl")
        self.skipExplLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.skipExplLbl.setGeometry(QtCore.QRect(330, 70, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.skipExplLbl.setFont(font)
        self.skipExplLbl.setObjectName("skipExplLbl")
        self.resetExplLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.resetExplLbl.setGeometry(QtCore.QRect(330, 110, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.resetExplLbl.setFont(font)
        self.resetExplLbl.setObjectName("resetExplLbl")
        self.tabWidget.addTab(self.visualizationControlsTab, "")
        Console.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Console)
        self.statusbar.setObjectName("statusbar")
        Console.setStatusBar(self.statusbar)

        self.retranslateUi(Console)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Console)

    def retranslateUi(self, Console):
        _translate = QtCore.QCoreApplication.translate
        Console.setWindowTitle(_translate("Console", "Graph Console"))
        self.delayLbl.setText(_translate("Console", "Step delay:"))
        self.visualizeBtn.setText(_translate("Console", "Visualize"))
        self.comboBox.setItemText(0, _translate("Console", "Breadth First Search (BFS)"))
        self.comboBox.setItemText(1, _translate("Console", "Depth First Search (DFS)"))
        self.comboBox.setItemText(2, _translate("Console", "Dijkstra\'s"))
        self.comboBox.setItemText(3, _translate("Console", "A*"))
        self.generateBtn.setText(_translate("Console", "Generate New Graph"))
        self.algorithmLbl.setText(_translate("Console", "Algorithm:"))
        self.stepDelayValueLbl.setText(_translate("Console", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controllerTab), _translate("Console", "Controller"))
        self.resetLbl.setText(_translate("Console", "Reset Graph"))
        self.skipLbl.setText(_translate("Console", "Skip Visualization"))
        self.endLbl.setText(_translate("Console", "End (Quit visualization)"))
        self.endExplLbl.setText(_translate("Console", "Escape"))
        self.skipExplLbl.setText(_translate("Console", "Space"))
        self.resetExplLbl.setText(_translate("Console", "Backspace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.visualizationControlsTab), _translate("Console", "Visualization Controls"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Console = QtWidgets.QMainWindow()
    ui = Ui_Console()
    ui.setupUi(Console)
    Console.show()
    sys.exit(app.exec_())
