# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'console.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import console_behavior

class Ui_Console(object):
    def setupUi(self, Console):
        Console.setObjectName("Console")
        Console.resize(525, 300)
        Console.setMinimumSize(QtCore.QSize(530, 300))
        Console.setMaximumSize(QtCore.QSize(530, 300))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        Console.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Console)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 530, 300))
        self.tabWidget.setMinimumSize(QtCore.QSize(530, 300))
        self.tabWidget.setMaximumSize(QtCore.QSize(530, 300))
        self.tabWidget.setObjectName("tabWidget")
        self.controllerTab = QtWidgets.QWidget()
        self.controllerTab.setObjectName("controllerTab")
        self.nodeCountLbl = QtWidgets.QLabel(self.controllerTab)
        self.nodeCountLbl.setGeometry(QtCore.QRect(20, 150, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(16)
        self.nodeCountLbl.setFont(font)
        self.nodeCountLbl.setObjectName("nodeCountLbl")
        self.visualizeBtn = QtWidgets.QPushButton(self.controllerTab)
        self.visualizeBtn.setEnabled(False)
        self.visualizeBtn.setGeometry(QtCore.QRect(250, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(16)
        self.visualizeBtn.setFont(font)
        self.visualizeBtn.setObjectName("visualizeBtn")
        self.nodeSldr = QtWidgets.QSlider(self.controllerTab)
        self.nodeSldr.setGeometry(QtCore.QRect(250, 150, 200, 30))
        self.nodeSldr.setMaximum(50)
        self.nodeSldr.setOrientation(QtCore.Qt.Horizontal)
        self.nodeSldr.setTickInterval(1)
        self.nodeSldr.setObjectName("nodeSldr")
        self.algorithmDropdown = QtWidgets.QComboBox(self.controllerTab)
        self.algorithmDropdown.setGeometry(QtCore.QRect(160, 10, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        self.algorithmDropdown.setFont(font)
        self.algorithmDropdown.setObjectName("algorithmDropdown")
        self.algorithmDropdown.addItem("")
        self.algorithmDropdown.addItem("")
        self.algorithmDropdown.addItem("")
        self.algorithmDropdown.addItem("")
        self.generateBtn = QtWidgets.QPushButton(self.controllerTab)
        self.generateBtn.setGeometry(QtCore.QRect(20, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(14)
        self.generateBtn.setFont(font)
        self.generateBtn.setObjectName("generateBtn")
        self.algorithmLbl = QtWidgets.QLabel(self.controllerTab)
        self.algorithmLbl.setGeometry(QtCore.QRect(20, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(16)
        self.algorithmLbl.setFont(font)
        self.algorithmLbl.setObjectName("algorithmLbl")
        self.nodeCountValueLbl = QtWidgets.QLabel(self.controllerTab)
        self.nodeCountValueLbl.setGeometry(QtCore.QRect(470, 140, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nodeCountValueLbl.setFont(font)
        self.nodeCountValueLbl.setObjectName("nodeCountValueLbl")
        self.edgeCountLbl = QtWidgets.QLabel(self.controllerTab)
        self.edgeCountLbl.setGeometry(QtCore.QRect(20, 200, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        font.setPointSize(16)
        self.edgeCountLbl.setFont(font)
        self.edgeCountLbl.setObjectName("edgeCountLbl")
        self.edgeSldr = QtWidgets.QSlider(self.controllerTab)
        self.edgeSldr.setGeometry(QtCore.QRect(250, 200, 196, 30))
        self.edgeSldr.setMaximum(0)
        self.edgeSldr.setOrientation(QtCore.Qt.Horizontal)
        self.edgeSldr.setTickInterval(1)
        self.edgeSldr.setObjectName("edgeSldr")
        self.edgeCountValueLbl = QtWidgets.QLabel(self.controllerTab)
        self.edgeCountValueLbl.setGeometry(QtCore.QRect(470, 190, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edgeCountValueLbl.setFont(font)
        self.edgeCountValueLbl.setObjectName("edgeCountValueLbl")
        self.tabWidget.addTab(self.controllerTab, "")
        self.visualizationControlsTab = QtWidgets.QWidget()
        self.visualizationControlsTab.setObjectName("visualizationControlsTab")
        self.resetLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.resetLbl.setGeometry(QtCore.QRect(30, 170, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.resetLbl.setFont(font)
        self.resetLbl.setObjectName("resetLbl")
        self.skipLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.skipLbl.setGeometry(QtCore.QRect(30, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.skipLbl.setFont(font)
        self.skipLbl.setObjectName("skipLbl")
        self.endLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.endLbl.setGeometry(QtCore.QRect(30, 40, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endLbl.setFont(font)
        self.endLbl.setObjectName("endLbl")
        self.endExplLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.endExplLbl.setGeometry(QtCore.QRect(320, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.endExplLbl.setFont(font)
        self.endExplLbl.setObjectName("endExplLbl")
        self.skipExplLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.skipExplLbl.setGeometry(QtCore.QRect(320, 100, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.skipExplLbl.setFont(font)
        self.skipExplLbl.setObjectName("skipExplLbl")
        self.resetExplLbl = QtWidgets.QLabel(self.visualizationControlsTab)
        self.resetExplLbl.setGeometry(QtCore.QRect(320, 170, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.resetExplLbl.setFont(font)
        self.resetExplLbl.setObjectName("resetExplLbl")
        self.tabWidget.addTab(self.visualizationControlsTab, "")
        Console.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Console)
        self.statusbar.setObjectName("statusbar")
        Console.setStatusBar(self.statusbar)

        self.retranslateUi(Console)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Console)

        # --- functionality --- #
        self.edgeSldr.valueChanged.connect(lambda: console_behavior.edgeSliderValueChanged(self.edgeSldr, self.edgeCountValueLbl))
        self.nodeSldr.valueChanged.connect(lambda: console_behavior.nodeSliderValueChanged(self.nodeSldr, self.edgeSldr, self.nodeCountValueLbl))

        self.generateBtn.clicked.connect(lambda: console_behavior.generateBtnClicked(self.nodeSldr.value(), self.edgeSldr.value()))
        #self.visualizeBtn.setEnabled(True)
        self.visualizeBtn.clicked.connect(lambda: console_behavior.visualizeBtnClicked(Console, self.algorithmDropdown.currentText()))

    def retranslateUi(self, Console):
        _translate = QtCore.QCoreApplication.translate
        Console.setWindowTitle(_translate("Console", "Graph Console"))
        self.nodeCountLbl.setText(_translate("Console", "Amount of nodes:"))
        self.visualizeBtn.setText(_translate("Console", "Visualize"))
        self.algorithmDropdown.setItemText(0, _translate("Console", "Breadth First Search (BFS)"))
        self.algorithmDropdown.setItemText(1, _translate("Console", "Depth First Search (DFS)"))
        self.algorithmDropdown.setItemText(2, _translate("Console", "Dijkstra\'s"))
        self.algorithmDropdown.setItemText(3, _translate("Console", "A*"))
        self.generateBtn.setText(_translate("Console", "Generate New Graph"))
        self.algorithmLbl.setText(_translate("Console", "Algorithm:"))
        self.nodeCountValueLbl.setText(_translate("Console", "0"))
        self.edgeCountLbl.setText(_translate("Console", "Amount of edges:"))
        self.edgeCountValueLbl.setText(_translate("Console", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controllerTab), _translate("Console", "Controller"))
        self.resetLbl.setText(_translate("Console", "Reset Graph"))
        self.skipLbl.setText(_translate("Console", "Skip Visualization"))
        self.endLbl.setText(_translate("Console", "End (Quit visualization)"))
        self.endExplLbl.setText(_translate("Console", "Escape"))
        self.skipExplLbl.setText(_translate("Console", "Space"))
        self.resetExplLbl.setText(_translate("Console", "Backspace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.visualizationControlsTab), _translate("Console", "Visualization Controls"))